# Generated by Django 5.1.7 on 2025-03-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resarve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destinations', models.CharField(max_length=50)),
                ('back_forth', models.BooleanField(default=False)),
                ('resarve_status', models.BooleanField(default=False)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('capicity', models.PositiveIntegerField()),
                ('number_fly', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destinations', models.CharField(max_length=50)),
                ('back_forth', models.BooleanField(default=False)),
                ('resarve_status', models.BooleanField(default=False)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('capicity', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=12, unique=True)),
                ('national_id', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destinations', models.CharField(max_length=50)),
                ('back_forth', models.BooleanField(default=False)),
                ('resarve_status', models.BooleanField(default=False)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('capicity', models.PositiveIntegerField()),
                ('number_fly', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resarve.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.AddField(
            model_name='bus',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resarve.customer'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resarve.customer'),
        ),
    ]
